### PR TITLE
Updated color of ion-icon in ion-chip, ion-chip outline, ion-item line in dark mode and used color variable instead of hardcoded color(#238p38r)

### PR DESCRIPTION
**Pull request by azkyakhan**
### Related Issues

Closes #

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

### CODE REVIEW

**Comment by azkyakhan** [comment]
fulfillment

**Review by dt2patel — CHANGES_REQUESTED** [review]
I am seeing a lot of repetitive code here. Lets discuss and find a way to make this simpler.

**Comment by azkyakhan** [comment]
> I am seeing a lot of repetitive code here. Lets discuss and find a way to make this simpler.

Ok sir

**Comment by azkyakhan** [comment]
> I am seeing a lot of repetitive code here. Let's discuss and find a way to make this simpler.

As per our discussion, I have made the suggested changes.
1. Refactored styling to unify classes.
https://github.com/hotwax/fulfillment/pull/57
2. Created border variable and used it throughout the app.

**Review by dt2patel — APPROVED** [review]

**Pull request merged**
